// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyDojgzxLM6r-FvhrF_NDWujYd79g-Sj0VE',
    appId: '1:3316518017:web:065632409bc1beb802d180',
    messagingSenderId: '3316518017',
    projectId: 'ecomm-8008b',
    authDomain: 'ecomm-8008b.firebaseapp.com',
    storageBucket: 'ecomm-8008b.appspot.com',
    measurementId: 'G-E05XQEYJFZ',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyD0IIzUf_V6PjVeQepzz46FX0hEfKOriCc',
    appId: '1:3316518017:android:c927e51704769e1002d180',
    messagingSenderId: '3316518017',
    projectId: 'ecomm-8008b',
    storageBucket: 'ecomm-8008b.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyAEiCy0Fww8QZVC9JIehRP3Nyn51JYTWyk',
    appId: '1:3316518017:ios:2c39d44b96c9973d02d180',
    messagingSenderId: '3316518017',
    projectId: 'ecomm-8008b',
    storageBucket: 'ecomm-8008b.appspot.com',
    iosBundleId: 'com.example.shopsmartAdminAr',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyAEiCy0Fww8QZVC9JIehRP3Nyn51JYTWyk',
    appId: '1:3316518017:ios:2c39d44b96c9973d02d180',
    messagingSenderId: '3316518017',
    projectId: 'ecomm-8008b',
    storageBucket: 'ecomm-8008b.appspot.com',
    iosBundleId: 'com.example.shopsmartAdminAr',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyDojgzxLM6r-FvhrF_NDWujYd79g-Sj0VE',
    appId: '1:3316518017:web:e7e19cba2776c5b002d180',
    messagingSenderId: '3316518017',
    projectId: 'ecomm-8008b',
    authDomain: 'ecomm-8008b.firebaseapp.com',
    storageBucket: 'ecomm-8008b.appspot.com',
    measurementId: 'G-CDWEZ1QYP1',
  );
}
